# Generated by Django 5.2.1 on 2026-07-06 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wait_type', models.CharField(choices=[('None', 'None'), ('Wait Expected', 'Wait Expected'), ('Booking Recommended', 'Booking Recommended'), ('Booking Required', 'Booking Required')], max_length=30)),
                ('meal_type', models.CharField(choices=[('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Snack', 'Snack')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.TextField(max_length=120)),
            ],
        ),
    ]
