# Generated by Django 5.2.1 on 2026-07-06 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Snack', 'Snack'), ('Bar', 'Bar')], max_length=10)),
                ('wait_type', models.CharField(choices=[('None', 'None'), ('Wait Expected', 'Wait Expected'), ('Long Wait Expected', 'Long Wait Expected'), ('Booking Recommended', 'Booking Recommended'), ('Booking Required', 'Booking Required')], max_length=30)),
                ('price_type', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Average'), ('$$$', 'Expensive')], max_length=5)),
                ('is_favorite', models.BooleanField()),
                ('blurb', models.TextField(max_length=120)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
