# Generated by Django 5.2.1 on 2026-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melbourne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_favorite',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='wait_type',
            field=models.CharField(choices=[('None', 'None'), ('Wait Expected', 'Wait Expected'), ('Long Wait Expected', 'Long Wait Expected'), ('Booking Recommended', 'Booking Recommended'), ('Booking Required', 'Booking Required')], max_length=30),
        ),
    ]
