# Generated by Django 5.2.1 on 2026-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melbourne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_type',
            field=models.CharField(choices=[('cover', 'Cover'), ('no_cover', 'No Cover')], default='cover', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='blurb',
            field=models.TextField(max_length=240),
        ),
    ]
