# Generated by Django 5.1.6 on 2025-02-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_add_timestamps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogEntry',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='writeup',
            new_name='article',
        ),
    ]
