# Generated by Django 5.1.6 on 2025-03-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero',
            field=models.ImageField(default='root/projects/noimage.png', upload_to='root/projects/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(default='https://moekakiryu.dev'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='root.article'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
