# Generated by Django 5.1.6 on 2025-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_project_hero_project_is_featured_project_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hero',
            field=models.ImageField(blank=True, upload_to='www/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='www/projects/'),
        ),
    ]
