# Generated by Django 5.1.7 on 2025-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_employer_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_spicy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
