# Generated by Django 5.1.7 on 2025-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_alter_employer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hero',
            field=models.FileField(blank=True, upload_to='www/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='www/projects/'),
        ),
    ]
