# Generated by Django 5.1.7 on 2025-05-27 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0013_alter_project_hero_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
