# Generated by Django 5.1.7 on 2025-05-27 16:53

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('www', '0015_fill_draft_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='draft_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

