# Generated by Django 5.1.6 on 2025-02-28 10:46

import uuid
from django.db import migrations, models

# Source: https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields
def get_uuid_generator(app, model):
    def gen_uuid(apps, schema_editor):
        ActiveModel = apps.get_model(app, model)

        for entry in ActiveModel.objects.all():
            entry.slug = uuid.uuid4()
            entry.save(update_fields=["slug"])

    return gen_uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_add_uuid_slug'),
    ]

    operations = [
        migrations.RunPython(
            get_uuid_generator('root', 'blogentry'),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            get_uuid_generator('root', 'project'),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
