# Generated by Django 5.1.6 on 2025-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_rename_blogentry_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='root/projects/noimage.png', upload_to='root/projects/'),
            preserve_default=False,
        ),
    ]
