# Generated by Django 5.1.6 on 2025-03-16 12:17

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_project_hero_alter_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', tinymce.models.HTMLField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root.employer')),
            ],
        ),
    ]
