# Generated by Django 5.1.7 on 2025-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_article_is_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
